# Generated by Django 5.0.3 on 2024-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('E', 'Earphone'), ('Ta', 'Tab'), ('Ot', 'Other')], max_length=2),
        ),
    ]
